Repository t0xic0der/syngrafias, pull requests merged in 2020-12, with the labels that each got.

#70 Rolled back nuisance theming for cell blocks
  static/jscn/syngrafias.js
  static/jscn/usagetips.js
Labels: bug

#71 Variable cell partition width
  static/jscn/split.min.js
  static/jscn/syngrafias.js
  templates/asciidoc.html
Labels: enhancement

#69 Added special read-only cards
  static/jscn/syngrafias.js
  templates/asciidoc.html
Labels: enhancement

#72 Save documents to client's local storage
  modules/servdocs.py
  static/jscn/syngrafias.js
  templates/asciidoc.html
Labels: enhancement

#78 Open documents from local storage
  static/jscn/syngrafias.js
  templates/asciidoc.html
Labels: enhancement

#86 Rewrote cell DOM creation with template literals
  static/jscn/syngrafias.js
Labels: bug, documentation

#66 Full height editor
  modules/servdocs.py
  static/jscn/unityMode.js
  templates/asciidoc.html
  templates/singleFile.html
Labels: enhancement

#90 Addressing suggestions and reviews
  modules/servdocs.py
  static/css3/semantic.min.css
  static/css3/syngrafias.css
  static/css3/themes/default/assets/fonts/icons.ttf
  static/css3/themes/default/assets/fonts/icons.woff
  static/css3/themes/default/assets/fonts/icons.woff2
  static/font/mono-rlar.ttf
  static/font/sans-bdit.ttf
  static/font/sans-bold.ttf
  static/font/sans-ital.ttf
  static/font/sans-rlar.ttf
  static/jscn/semantic.min.js
  static/jscn/syngrafias.js
  static/jscn/unityMode.js
  templates/asciidoc.html
  templates/singleFile.html
Labels: bug, enhancement
